// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbquXp2kbCX-N64eMu0-gy-5XvR4fu4MY',
    appId: '1:780043849604:web:bc7126d06d8a02921597d1',
    messagingSenderId: '780043849604',
    projectId: 'bigmart-202f8',
    authDomain: 'bigmart-202f8.firebaseapp.com',
    storageBucket: 'bigmart-202f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvR9204MU_18VG21kwLu4M4-TPX4c0iw',
    appId: '1:780043849604:android:ae8dd29e2620315f1597d1',
    messagingSenderId: '780043849604',
    projectId: 'bigmart-202f8',
    storageBucket: 'bigmart-202f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDZnkucEshFgoqOGwVMMEn3hv8VkC4Ww',
    appId: '1:780043849604:ios:6048f160ad6a8a3e1597d1',
    messagingSenderId: '780043849604',
    projectId: 'bigmart-202f8',
    storageBucket: 'bigmart-202f8.appspot.com',
    iosBundleId: 'com.example.bigmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiDZnkucEshFgoqOGwVMMEn3hv8VkC4Ww',
    appId: '1:780043849604:ios:f86a371ce7c6553e1597d1',
    messagingSenderId: '780043849604',
    projectId: 'bigmart-202f8',
    storageBucket: 'bigmart-202f8.appspot.com',
    iosBundleId: 'com.example.bigmart.RunnerTests',
  );
}
